# YouTube Video Speed Controller style speed controls
s add speed -0.1
d add speed 0.1

# Precise seeking
RIGHT seek 0.2 exact
LEFT  seek -0.2 exact
UP    seek 0.02 exact
DOWN  seek -0.02 exact
.     seek 1.00 relative+exact
,     seek -1.00 relative+exact

